Removed nose imports in test_runner.py
angr/tracer pull request #84
Opened 2022-03-30 19:22 UTC by mohitrpatil

2022-03-30 19:44 UTC, twizmwazin reviewed
test_runner.py looks good. Since this repo only has a few test files, can you do this for the rest of them and add them to this PR, and then re-request a review when that's ready?

2022-03-30 19:48 UTC, mohitrpatil commented
> test_runner.py looks good. Since this repo only has a few test files, can you do this for the rest of them and add them to this PR, and then re-request a review when that's ready?

2022-04-04 22:17 UTC, twizmwazin requested changes
Looks like you missed one in test_cache_stall. The `@attr` decorator can just be replaced by setting `func.speed = "slow"` after the function is defined.

2022-04-04 23:50 UTC, twizmwazin approved these changes

2022-04-04 23:51 UTC, merged